@startuml
title "class-diagram: private Dictionary"
class Runner{
    void hello()
    void main()
}
interface StorageFace{
    String source
    String storage
    String getStorage()
    void setStorage(String path)
    void get(String path)
    void put(File file)
}
interface UserFace{
    void setSourcePath(String path)
    void showPaths()
    void showReports()
    void repeat()
    void help()
    void quit()
}
class Dictionary{
    HashMap words
    String text
    dictionary(String[] text)
}

@enduml