@startuml
title "Описание методов частного словаря"
participant "Пользователь" as user
participant "Программа" as app
participant "Хранилище" as storage

user -> app : "Запуск программы"
app -> user : "Приветствие пользвателя"
storage -> app : "Инструкции:\nпорядок взаимодействия с программой"
app -> user : "Инструкции:\nпорядок взаимодействия с программой"
user -> app : "Путь к файлу\n с исходным текстом"
storage -> app : "Данные из файла с исходным текстом"
app -> app : "Обработка исходных данных"
app -> storage : "Файлы с отчетами:\nрезультаты анализа текста"
app -> user : "Пути к файлам с отчетами"
app -> user : "Предложение:\nуказать путь к новому исходному тексту"
app -> user : "Предложение:\nзавершиь работу программы (quit)"
user -> app : "quit"
@enduml